using Microsoft.EntityFrameworkCore;
using VirtualBar.Domain.Entities;
using VirtualBar.Domain.Enums;

namespace VirtualBar.Infrastructure.Persistence;

public static class DistillerySeeder
{
    public static async Task SeedDistilleriesAsync(AppDbContext db, CancellationToken cancellationToken = default)
    {
        var hasDistilleries = await db.Distilleries.AnyAsync(cancellationToken);
        var hasCategories = await db.DistilleryCategories.AnyAsync(cancellationToken);

        if (!hasDistilleries)
        {
            var now = DateTime.UtcNow;

            var uniqueDistilleries = data
                .GroupBy(d => d.Name)
                .Select(g => g.First())
                .Select(d => new Distillery
                {
                    Id = Guid.NewGuid(),
                    Name = d.Name,
                    Country = d.Country,
                    Region = d.Region,
                    CreatedAt = now,
                    UpdatedAt = now
                })
                .ToList();

            db.Distilleries.AddRange(uniqueDistilleries);
            await db.SaveChangesAsync(cancellationToken);

            var idByName = uniqueDistilleries.ToDictionary(d => d.Name, d => d.Id);

            var categories = data
                .GroupBy(d => (d.Name, d.Category))
                .Select(g => g.First())
                .Select(d => new DistilleryCategory
                {
                    DistilleryId = idByName[d.Name],
                    Category = d.Category
                })
                .ToList();

            db.DistilleryCategories.AddRange(categories);
            await db.SaveChangesAsync(cancellationToken);
        }
        else if (!hasCategories)
        {
            var names = data.Select(d => d.Name).Distinct().ToList();
            var existing = await db.Distilleries
                .Where(d => names.Contains(d.Name))
                .ToListAsync(cancellationToken);

            var idByName = existing.ToDictionary(d => d.Name, d => d.Id);

            var categories = data
                .Where(d => idByName.ContainsKey(d.Name))
                .GroupBy(d => (d.Name, d.Category))
                .Select(g => g.First())
                .Select(d => new DistilleryCategory
                {
                    DistilleryId = idByName[d.Name],
                    Category = d.Category
                })
                .ToList();

            db.DistilleryCategories.AddRange(categories);
            await db.SaveChangesAsync(cancellationToken);
        }
    }

    private static readonly (string Name, string Country, string? Region, SpiritCategory Category)[] data =
    {
        ("Glenfiddich", "Scotland", null, SpiritCategory.Whisky),
        ("Macallan", "Scotland", null, SpiritCategory.Whisky),
        ("Glenlivet", "Scotland", null, SpiritCategory.Whisky),
        ("Lagavulin", "Scotland", null, SpiritCategory.Whisky),
        ("Laphroaig", "Scotland", null, SpiritCategory.Whisky),
        ("Ardbeg", "Scotland", null, SpiritCategory.Whisky),
        ("Talisker", "Scotland", null, SpiritCategory.Whisky),
        ("Oban", "Scotland", null, SpiritCategory.Whisky),
        ("Dalmore", "Scotland", null, SpiritCategory.Whisky),
        ("Highland Park", "Scotland", null, SpiritCategory.Whisky),
        ("Balvenie", "Scotland", null, SpiritCategory.Whisky),
        ("Aberlour", "Scotland", null, SpiritCategory.Whisky),
        ("Glenmorangie", "Scotland", null, SpiritCategory.Whisky),
        ("Bowmore", "Scotland", null, SpiritCategory.Whisky),
        ("Caol Ila", "Scotland", null, SpiritCategory.Whisky),
        ("Bunnahabhain", "Scotland", null, SpiritCategory.Whisky),
        ("Bruichladdich", "Scotland", null, SpiritCategory.Whisky),
        ("Kilchoman", "Scotland", null, SpiritCategory.Whisky),
        ("Springbank", "Scotland", null, SpiritCategory.Whisky),
        ("Longrow", "Scotland", null, SpiritCategory.Whisky),
        ("Hazelburn", "Scotland", null, SpiritCategory.Whisky),
        ("BenRiach", "Scotland", null, SpiritCategory.Whisky),
        ("Glendronach", "Scotland", null, SpiritCategory.Whisky),
        ("GlenAllachie", "Scotland", null, SpiritCategory.Whisky),
        ("Tomatin", "Scotland", null, SpiritCategory.Whisky),
        ("Deanston", "Scotland", null, SpiritCategory.Whisky),
        ("Tullibardine", "Scotland", null, SpiritCategory.Whisky),
        ("Edradour", "Scotland", null, SpiritCategory.Whisky),
        ("Ben Nevis", "Scotland", null, SpiritCategory.Whisky),
        ("Arran", "Scotland", null, SpiritCategory.Whisky),
        ("Jura", "Scotland", null, SpiritCategory.Whisky),
        ("Tobermory", "Scotland", null, SpiritCategory.Whisky),
        ("Ardnamurchan", "Scotland", null, SpiritCategory.Whisky),
        ("Clynelish", "Scotland", null, SpiritCategory.Whisky),
        ("Royal Lochnagar", "Scotland", null, SpiritCategory.Whisky),
        ("Blair Athol", "Scotland", null, SpiritCategory.Whisky),
        ("Mortlach", "Scotland", null, SpiritCategory.Whisky),
        ("Cragganmore", "Scotland", null, SpiritCategory.Whisky),
        ("Cardhu", "Scotland", null, SpiritCategory.Whisky),
        ("Glenfarclas", "Scotland", null, SpiritCategory.Whisky),
        ("Knockando", "Scotland", null, SpiritCategory.Whisky),
        ("Benromach", "Scotland", null, SpiritCategory.Whisky),
        ("Glen Scotia", "Scotland", null, SpiritCategory.Whisky),
        ("Scapa", "Scotland", null, SpiritCategory.Whisky),
        ("Linkwood", "Scotland", null, SpiritCategory.Whisky),
        ("Glen Grant", "Scotland", null, SpiritCategory.Whisky),
        ("Aultmore", "Scotland", null, SpiritCategory.Whisky),
        ("Dailuaine", "Scotland", null, SpiritCategory.Whisky),
        ("Inchgower", "Scotland", null, SpiritCategory.Whisky),
        ("Teaninich", "Scotland", null, SpiritCategory.Whisky),

        ("Midleton", "Ireland", null, SpiritCategory.Whisky),
        ("Jameson Distillery", "Ireland", null, SpiritCategory.Whisky),
        ("Bushmills", "Ireland", null, SpiritCategory.Whisky),
        ("Teeling", "Ireland", null, SpiritCategory.Whisky),
        ("Tullamore D.E.W.", "Ireland", null, SpiritCategory.Whisky),
        ("Powers", "Ireland", null, SpiritCategory.Whisky),
        ("Redbreast", "Ireland", null, SpiritCategory.Whisky),
        ("Green Spot", "Ireland", null, SpiritCategory.Whisky),
        ("Yellow Spot", "Ireland", null, SpiritCategory.Whisky),
        ("Dingle", "Ireland", null, SpiritCategory.Whisky),
        ("Waterford", "Ireland", null, SpiritCategory.Whisky),
        ("Slane", "Ireland", null, SpiritCategory.Whisky),
        ("Roe & Co", "Ireland", null, SpiritCategory.Whisky),
        ("Kilbeggan", "Ireland", null, SpiritCategory.Whisky),
        ("Cooley", "Ireland", null, SpiritCategory.Whisky),
        ("Writer's Tears", "Ireland", null, SpiritCategory.Whisky),
        ("Walsh Whiskey", "Ireland", null, SpiritCategory.Whisky),
        ("Glendalough", "Ireland", null, SpiritCategory.Whisky),
        ("Blackwater", "Ireland", null, SpiritCategory.Whisky),
        ("Boann", "Ireland", null, SpiritCategory.Whisky),

        ("Buffalo Trace", "USA", null, SpiritCategory.Whisky),
        ("Maker's Mark", "USA", null, SpiritCategory.Whisky),
        ("Woodford Reserve", "USA", null, SpiritCategory.Whisky),
        ("Wild Turkey", "USA", null, SpiritCategory.Whisky),
        ("Four Roses", "USA", null, SpiritCategory.Whisky),
        ("Heaven Hill", "USA", null, SpiritCategory.Whisky),
        ("Jim Beam", "USA", null, SpiritCategory.Whisky),
        ("Knob Creek", "USA", null, SpiritCategory.Whisky),
        ("Basil Hayden", "USA", null, SpiritCategory.Whisky),
        ("Booker's", "USA", null, SpiritCategory.Whisky),
        ("Elijah Craig", "USA", null, SpiritCategory.Whisky),
        ("Old Forester", "USA", null, SpiritCategory.Whisky),
        ("Evan Williams", "USA", null, SpiritCategory.Whisky),
        ("Angel's Envy", "USA", null, SpiritCategory.Whisky),
        ("Rabbit Hole", "USA", null, SpiritCategory.Whisky),
        ("Michter's", "USA", null, SpiritCategory.Whisky),
        ("Stagg", "USA", null, SpiritCategory.Whisky),
        ("Blanton's", "USA", null, SpiritCategory.Whisky),
        ("Pappy Van Winkle", "USA", null, SpiritCategory.Whisky),
        ("Bulleit", "USA", null, SpiritCategory.Whisky),
        ("Jack Daniel's", "USA", null, SpiritCategory.Whisky),
        ("George Dickel", "USA", null, SpiritCategory.Whisky),
        ("Chattanooga Whiskey", "USA", null, SpiritCategory.Whisky),
        ("New Riff", "USA", null, SpiritCategory.Whisky),
        ("Bardstown Bourbon", "USA", null, SpiritCategory.Whisky),
        ("Widow Jane", "USA", null, SpiritCategory.Whisky),
        ("WhistlePig", "USA", null, SpiritCategory.Whisky),
        ("Jefferson's", "USA", null, SpiritCategory.Whisky),
        ("Smooth Ambler", "USA", null, SpiritCategory.Whisky),
        ("Peerless", "USA", null, SpiritCategory.Whisky),

        ("Yamazaki", "Japan", null, SpiritCategory.Whisky),
        ("Hakushu", "Japan", null, SpiritCategory.Whisky),
        ("Chita", "Japan", null, SpiritCategory.Whisky),
        ("Yoichi", "Japan", null, SpiritCategory.Whisky),
        ("Miyagikyo", "Japan", null, SpiritCategory.Whisky),
        ("Nikka", "Japan", null, SpiritCategory.Whisky),
        ("Mars Shinshu", "Japan", null, SpiritCategory.Whisky),
        ("Tsunuki", "Japan", null, SpiritCategory.Whisky),
        ("Akkeshi", "Japan", null, SpiritCategory.Whisky),
        ("Kanosuke", "Japan", null, SpiritCategory.Whisky),
        ("Shizuoka", "Japan", null, SpiritCategory.Whisky),
        ("Sakurao", "Japan", null, SpiritCategory.Whisky),
        ("Eigashima", "Japan", null, SpiritCategory.Whisky),
        ("White Oak", "Japan", null, SpiritCategory.Whisky),
        ("Hanyu", "Japan", null, SpiritCategory.Whisky),
        ("Chichibu", "Japan", null, SpiritCategory.Whisky),
        ("Fuji Gotemba", "Japan", null, SpiritCategory.Whisky),
        ("Kirin", "Japan", null, SpiritCategory.Whisky),
        ("Nagahama", "Japan", null, SpiritCategory.Whisky),
        ("Asaka", "Japan", null, SpiritCategory.Whisky),

        ("Crown Royal", "Canada", null, SpiritCategory.Whisky),
        ("Canadian Club", "Canada", null, SpiritCategory.Whisky),
        ("Forty Creek", "Canada", null, SpiritCategory.Whisky),
        ("Lot No. 40", "Canada", null, SpiritCategory.Whisky),
        ("Pike Creek", "Canada", null, SpiritCategory.Whisky),
        ("Gooderham & Worts", "Canada", null, SpiritCategory.Whisky),
        ("J.P. Wiser's", "Canada", null, SpiritCategory.Whisky),
        ("Alberta Premium", "Canada", null, SpiritCategory.Whisky),
        ("Shelter Point", "Canada", null, SpiritCategory.Whisky),
        ("Wayne Gretzky Distillery", "Canada", null, SpiritCategory.Whisky),

        ("Amrut", "India", null, SpiritCategory.Whisky),
        ("Paul John", "India", null, SpiritCategory.Whisky),
        ("Rampur", "India", null, SpiritCategory.Whisky),
        ("Indri", "India", null, SpiritCategory.Whisky),
        ("Kamet", "India", null, SpiritCategory.Whisky),
        ("Godawan", "India", null, SpiritCategory.Whisky),
        ("GianChand", "India", null, SpiritCategory.Whisky),
        ("Woodburns", "India", null, SpiritCategory.Whisky),
        ("Longitude 77", "India", null, SpiritCategory.Whisky),
        ("Crazy Cock", "India", null, SpiritCategory.Whisky),

        ("Kavalan", "Taiwan", null, SpiritCategory.Whisky),
        ("Omar", "Taiwan", null, SpiritCategory.Whisky),
        ("Nantou", "Taiwan", null, SpiritCategory.Whisky),
        ("Yushan", "Taiwan", null, SpiritCategory.Whisky),
        ("King Car", "Taiwan", null, SpiritCategory.Whisky),

        ("Starward", "Australia", null, SpiritCategory.Whisky),
        ("Sullivan's Cove", "Australia", null, SpiritCategory.Whisky),
        ("Hellyers Road", "Australia", null, SpiritCategory.Whisky),
        ("Lark", "Australia", null, SpiritCategory.Whisky),
        ("Overeem", "Australia", null, SpiritCategory.Whisky),
        ("Archie Rose", "Australia", null, SpiritCategory.Whisky),
        ("Bakery Hill", "Australia", null, SpiritCategory.Whisky),
        ("Limeburners", "Australia", null, SpiritCategory.Whisky),
        ("Nant", "Australia", null, SpiritCategory.Whisky),
        ("Belgrove", "Australia", null, SpiritCategory.Whisky),

        ("Rozelieures", "France", null, SpiritCategory.Whisky),
        ("Armorik", "France", null, SpiritCategory.Whisky),
        ("Brenne", "France", null, SpiritCategory.Whisky),
        ("Distillerie Warenghem", "France", null, SpiritCategory.Whisky),
        ("Domaine des Hautes Glaces", "France", null, SpiritCategory.Whisky),

        ("Mackmyra", "Sweden", null, SpiritCategory.Whisky),
        ("High Coast", "Sweden", null, SpiritCategory.Whisky),
        ("Smögen", "Sweden", null, SpiritCategory.Whisky),
        ("Spirit of Hven", "Sweden", null, SpiritCategory.Whisky),
        ("Box Distillery", "Sweden", null, SpiritCategory.Whisky),

        ("Slyrs", "Germany", null, SpiritCategory.Whisky),
        ("St. Kilian", "Germany", null, SpiritCategory.Whisky),
        ("Elsburn", "Germany", null, SpiritCategory.Whisky),
        ("Finch", "Germany", null, SpiritCategory.Whisky),
        ("Hammerschmiede", "Germany", null, SpiritCategory.Whisky),

        ("Millstone", "Netherlands", null, SpiritCategory.Whisky),
        ("Zuidam", "Netherlands", null, SpiritCategory.Whisky),
        ("Frysk Hynder", "Netherlands", null, SpiritCategory.Whisky),
        ("Wagging Finger", "Netherlands", null, SpiritCategory.Whisky),
        ("Dutch Courage", "Netherlands", null, SpiritCategory.Whisky),

        ("Cardrona", "New Zealand", null, SpiritCategory.Whisky),
        ("Thomson", "New Zealand", null, SpiritCategory.Whisky),
        ("Pōkeno", "New Zealand", null, SpiritCategory.Whisky),
        ("New Zealand Whisky Collection", "New Zealand", null, SpiritCategory.Whisky),
        ("Lammerlaw", "New Zealand", null, SpiritCategory.Whisky),

        ("Bain's", "South Africa", null, SpiritCategory.Whisky),
        ("Three Ships", "South Africa", null, SpiritCategory.Whisky),
        ("Drayman's", "South Africa", null, SpiritCategory.Whisky),
        ("James Sedgwick", "South Africa", null, SpiritCategory.Whisky),
        ("Boplaas", "South Africa", null, SpiritCategory.Whisky),

        ("Penderyn", "Wales", null, SpiritCategory.Whisky),
        ("Aber Falls", "Wales", null, SpiritCategory.Whisky),
        ("Dà Mhìle", "Wales", null, SpiritCategory.Whisky),
        ("Coles", "Wales", null, SpiritCategory.Whisky),
        ("In the Welsh Wind", "Wales", null, SpiritCategory.Whisky),

        ("Milk & Honey", "Israel", null, SpiritCategory.Whisky),
        ("Golan Heights Distillery", "Israel", null, SpiritCategory.Whisky),

        ("Cotswolds", "England", null, SpiritCategory.Whisky),
        ("The English Distillery", "England", null, SpiritCategory.Whisky),
        ("Adnams", "England", null, SpiritCategory.Whisky),
        ("Bimber", "England", null, SpiritCategory.Whisky),
        ("East London Liquor Company", "England", null, SpiritCategory.Whisky),
        ("Spirit of Yorkshire", "England", null, SpiritCategory.Whisky),
        ("White Peak Distillery", "England", null, SpiritCategory.Whisky),

        ("Foursquare", "Barbados", null, SpiritCategory.Rum),
        ("Appleton Estate", "Jamaica", null, SpiritCategory.Rum),
        ("Mount Gay", "Barbados", null, SpiritCategory.Rum),
        ("Hampden Estate", "Jamaica", null, SpiritCategory.Rum),
        ("Bacardi", "Puerto Rico", null, SpiritCategory.Rum),
        ("Flor de Caña", "Nicaragua", null, SpiritCategory.Rum),
        ("Havana Club", "Cuba", null, SpiritCategory.Rum),
        ("Diplomatico", "Venezuela", null, SpiritCategory.Rum),
        ("El Dorado", "Guyana", null, SpiritCategory.Rum),
        ("Zacapa", "Guatemala", null, SpiritCategory.Rum),
        ("Bumbu", "Barbados", null, SpiritCategory.Rum),
        ("Worthy Park", "Jamaica", null, SpiritCategory.Rum),
        ("Brugal", "Dominican Republic", null, SpiritCategory.Rum),
        ("Don Q", "Puerto Rico", null, SpiritCategory.Rum),
        ("Saint Lucia Distillers", "Saint Lucia", null, SpiritCategory.Rum),
        ("Angostura", "Trinidad and Tobago", null, SpiritCategory.Rum),
        ("Clément", "Martinique", null, SpiritCategory.Rum),
        ("Rhum J.M", "Martinique", null, SpiritCategory.Rum),
        ("Abuelo", "Panama", null, SpiritCategory.Rum),
        ("Santa Teresa", "Venezuela", null, SpiritCategory.Rum),
        ("Barceló", "Dominican Republic", null, SpiritCategory.Rum),
        ("Botran", "Guatemala", null, SpiritCategory.Rum),
        ("Damoiseau", "Guadeloupe", null, SpiritCategory.Rum),
        ("Neisson", "Martinique", null, SpiritCategory.Rum),
        ("La Favorite", "Martinique", null, SpiritCategory.Rum),
        ("Savanna", "Réunion", null, SpiritCategory.Rum),
        ("Longueteau", "Guadeloupe", null, SpiritCategory.Rum),
        ("English Harbour", "Antigua", null, SpiritCategory.Rum),
        ("Dictador", "Colombia", null, SpiritCategory.Rum),
        ("La Hechicera", "Colombia", null, SpiritCategory.Rum),
        ("West Indies Rum Distillery", "Barbados", null, SpiritCategory.Rum),
        ("St. Nicholas Abbey", "Barbados", null, SpiritCategory.Rum),
        ("Chairman's Reserve", "Saint Lucia", null, SpiritCategory.Rum),
        ("Planteray", "France", null, SpiritCategory.Rum),
        ("Pusser's", "British Virgin Islands", null, SpiritCategory.Rum),
        ("Black Tot", "United Kingdom", null, SpiritCategory.Rum),
        ("Paranubes", "Mexico", null, SpiritCategory.Rum),
        ("River Antoine", "Grenada", null, SpiritCategory.Rum),
        ("Goslings", "Bermuda", null, SpiritCategory.Rum),
        ("Trois Rivières", "Martinique", null, SpiritCategory.Rum),
        ("Depaz", "Martinique", null, SpiritCategory.Rum),
        ("Bologne", "Guadeloupe", null, SpiritCategory.Rum),
        ("Chamarel", "Mauritius", null, SpiritCategory.Rum),
        ("New Grove", "Mauritius", null, SpiritCategory.Rum),
        ("Tanduay", "Philippines", null, SpiritCategory.Rum),
        ("Don Papa", "Philippines", null, SpiritCategory.Rum),
        ("Richland", "USA", null, SpiritCategory.Rum),
        ("Privateer", "USA", null, SpiritCategory.Rum),
        ("Kō Hana", "USA", null, SpiritCategory.Rum),
        ("Holmes Cay", "USA", null, SpiritCategory.Rum),
        ("Long Pond", "Jamaica", null, SpiritCategory.Rum),
        ("Clarendon", "Jamaica", null, SpiritCategory.Rum),
        ("Monymusk", "Jamaica", null, SpiritCategory.Rum),
        ("Papalin", "Italy", null, SpiritCategory.Rum),
        ("Habitation Velier", "Italy", null, SpiritCategory.Rum),
        ("Compagnie des Indes", "France", null, SpiritCategory.Rum),
        ("Rum Nation", "Italy", null, SpiritCategory.Rum),
        ("Transcontinental Rum Line", "France", null, SpiritCategory.Rum),
        ("Equiano", "Barbados", null, SpiritCategory.Rum),
        ("Grays Distilling", "Mauritius", null, SpiritCategory.Rum),
        ("Nine Leaves", "Japan", null, SpiritCategory.Rum),
        ("Mhoba", "South Africa", null, SpiritCategory.Rum),
        ("Bielle", "Guadeloupe", null, SpiritCategory.Rum),
        ("Bellevue", "Guadeloupe", null, SpiritCategory.Rum),
        ("Karukera", "Guadeloupe", null, SpiritCategory.Rum),
        ("Père Labat", "Guadeloupe", null, SpiritCategory.Rum),
        ("Isautier", "Réunion", null, SpiritCategory.Rum),
        ("Rivière du Mât", "Réunion", null, SpiritCategory.Rum),
        ("Père Labat Marie-Galante", "Guadeloupe", null, SpiritCategory.Rum),
        ("Bayou Rum", "USA", null, SpiritCategory.Rum),
        ("Cutwater", "USA", null, SpiritCategory.Rum),
        ("Siesta Key", "USA", null, SpiritCategory.Rum),
        ("Montanya", "USA", null, SpiritCategory.Rum),
        ("Copalli", "Belize", null, SpiritCategory.Rum),
        ("Matusalem", "Dominican Republic", null, SpiritCategory.Rum),
        ("Santiago de Cuba", "Cuba", null, SpiritCategory.Rum),
        ("Legendario", "Cuba", null, SpiritCategory.Rum),
        ("Arehucas", "Spain", null, SpiritCategory.Rum),
        ("Ron Millonario", "Peru", null, SpiritCategory.Rum),
        ("Cihuatán", "El Salvador", null, SpiritCategory.Rum),
        ("Malecon", "Panama", null, SpiritCategory.Rum),
        ("Travellers", "Belize", null, SpiritCategory.Rum),
        ("Copeland Rum", "United Kingdom", null, SpiritCategory.Rum),
        ("Admiral Rodney", "Saint Lucia", null, SpiritCategory.Rum),
        ("Takamaka", "Seychelles", null, SpiritCategory.Rum),
        ("Cloven Hoof", "United Kingdom", null, SpiritCategory.Rum),
        ("Elements Eight", "Saint Lucia", null, SpiritCategory.Rum),
        ("Westerhall", "Grenada", null, SpiritCategory.Rum),
        ("Belmont Estate", "Grenada", null, SpiritCategory.Rum),
        ("Sunset Very Strong Rum", "Saint Vincent", null, SpiritCategory.Rum),
        ("Rum Fire", "Jamaica", null, SpiritCategory.Rum),
        ("Wray & Nephew", "Jamaica", null, SpiritCategory.Rum),
        ("Rum-Bar", "Jamaica", null, SpiritCategory.Rum),
        ("El Pasador de Oro", "Guatemala", null, SpiritCategory.Rum),
        ("O Reizinho", "Portugal", null, SpiritCategory.Rum),
        ("William Hinton", "Portugal", null, SpiritCategory.Rum),
        ("Madeira Rum House", "Portugal", null, SpiritCategory.Rum),
        ("Engenhos do Norte", "Portugal", null, SpiritCategory.Rum),
        ("Barbosa Amado", "Portugal", null, SpiritCategory.Rum),
        ("ReimonenQ", "Guadeloupe", null, SpiritCategory.Rum),

        ("Grey Goose", "France", null, SpiritCategory.Vodka),
        ("Belvedere", "Poland", null, SpiritCategory.Vodka),
        ("Absolut", "Sweden", null, SpiritCategory.Vodka),
        ("Ketel One", "Netherlands", null, SpiritCategory.Vodka),
        ("Chopin", "Poland", null, SpiritCategory.Vodka),
        ("Cîroc", "France", null, SpiritCategory.Vodka),
        ("Stolichnaya", "Latvia", null, SpiritCategory.Vodka),
        ("Finlandia", "Finland", null, SpiritCategory.Vodka),
        ("Russian Standard", "Russia", null, SpiritCategory.Vodka),
        ("Crystal Head", "Canada", null, SpiritCategory.Vodka),
        ("Tito's Handmade Vodka", "USA", null, SpiritCategory.Vodka),
        ("Reyka", "Iceland", null, SpiritCategory.Vodka),
        ("Wyborowa", "Poland", null, SpiritCategory.Vodka),
        ("Żubrówka", "Poland", null, SpiritCategory.Vodka),
        ("Beluga", "Russia", null, SpiritCategory.Vodka),
        ("Purity Vodka", "Sweden", null, SpiritCategory.Vodka),
        ("Haku", "Japan", null, SpiritCategory.Vodka),
        ("Nikka Coffey Vodka", "Japan", null, SpiritCategory.Vodka),
        ("Koskenkorva", "Finland", null, SpiritCategory.Vodka),
        ("Skyy", "USA", null, SpiritCategory.Vodka),
        ("Smirnoff", "United Kingdom", null, SpiritCategory.Vodka),
        ("Eristoff", "Georgia", null, SpiritCategory.Vodka),
        ("Nemiroff", "Ukraine", null, SpiritCategory.Vodka),
        ("Kauffman", "Russia", null, SpiritCategory.Vodka),
        ("Snow Leopard", "Poland", null, SpiritCategory.Vodka),
        ("Sobieski", "Poland", null, SpiritCategory.Vodka),
        ("Luksusowa", "Poland", null, SpiritCategory.Vodka),
        ("Żytnia", "Poland", null, SpiritCategory.Vodka),
        ("Pravda", "Poland", null, SpiritCategory.Vodka),
        ("Danzka", "Denmark", null, SpiritCategory.Vodka),
        ("Vikingfjord", "Norway", null, SpiritCategory.Vodka),
        ("Hammer & Sickle", "Russia", null, SpiritCategory.Vodka),
        ("Moskovskaya", "Russia", null, SpiritCategory.Vodka),
        ("Green Mark", "Russia", null, SpiritCategory.Vodka),
        ("Parliament", "Ukraine", null, SpiritCategory.Vodka),
        ("Khor", "Ukraine", null, SpiritCategory.Vodka),
        ("Khor Platinum", "Ukraine", null, SpiritCategory.Vodka),
        ("Onegin", "Russia", null, SpiritCategory.Vodka),
        ("Organika", "Russia", null, SpiritCategory.Vodka),
        ("Mamont", "Russia", null, SpiritCategory.Vodka),
        ("Zyr", "Russia", null, SpiritCategory.Vodka),
        ("Our/Vodka", "Germany", null, SpiritCategory.Vodka),
        ("Illusion", "United Kingdom", null, SpiritCategory.Vodka),
        ("Black Cow", "United Kingdom", null, SpiritCategory.Vodka),
        ("East London Liquor Vodka", "United Kingdom", null, SpiritCategory.Vodka),
        ("Sapling Vodka", "United Kingdom", null, SpiritCategory.Vodka),
        ("Chase Vodka", "United Kingdom", null, SpiritCategory.Vodka),
        ("Cotswolds Vodka", "United Kingdom", null, SpiritCategory.Vodka),
        ("Boatyard Vodka", "United Kingdom", null, SpiritCategory.Vodka),
        ("Broken Clock", "Canada", null, SpiritCategory.Vodka),
        ("Iceberg Vodka", "Canada", null, SpiritCategory.Vodka),
        ("Polar Ice", "Canada", null, SpiritCategory.Vodka),
        ("Crystal Head Aurora", "Canada", null, SpiritCategory.Vodka),
        ("Deep Eddy", "USA", null, SpiritCategory.Vodka),
        ("New Amsterdam", "USA", null, SpiritCategory.Vodka),
        ("Prairie Organic", "USA", null, SpiritCategory.Vodka),
        ("Hangar 1", "USA", null, SpiritCategory.Vodka),
        ("Boyd & Blair", "USA", null, SpiritCategory.Vodka),
        ("Wheatley Vodka", "USA", null, SpiritCategory.Vodka),
        ("Ocean Vodka", "USA", null, SpiritCategory.Vodka),
        ("44° North", "USA", null, SpiritCategory.Vodka),
        ("Dixie Vodka", "USA", null, SpiritCategory.Vodka),
        ("Stateside Vodka", "USA", null, SpiritCategory.Vodka),
        ("Hella Cocktail Vodka", "USA", null, SpiritCategory.Vodka),
        ("Hanson of Sonoma", "USA", null, SpiritCategory.Vodka),
        ("Masons Vodka", "United Kingdom", null, SpiritCategory.Vodka),
        ("Ramsbury Vodka", "United Kingdom", null, SpiritCategory.Vodka),
        ("Edwards 1902", "United Kingdom", null, SpiritCategory.Vodka),
        ("Silent Pool Vodka", "United Kingdom", null, SpiritCategory.Vodka),
        ("Vestal", "Poland", null, SpiritCategory.Vodka),
        ("U'Luvka", "Poland", null, SpiritCategory.Vodka),
        ("Krupnik Vodka", "Poland", null, SpiritCategory.Vodka),
        ("Pan Tadeusz", "Poland", null, SpiritCategory.Vodka),
        ("Baczewski Vodka", "Poland", null, SpiritCategory.Vodka),
        ("Debowa Vodka", "Poland", null, SpiritCategory.Vodka),
        ("Altia Vodka", "Finland", null, SpiritCategory.Vodka),
        ("Laplandia", "Finland", null, SpiritCategory.Vodka),
        ("Saimaa Vodka", "Finland", null, SpiritCategory.Vodka),
        ("Arctic Blue Vodka", "Finland", null, SpiritCategory.Vodka),
        ("Karlsson's Vodka", "Sweden", null, SpiritCategory.Vodka),
        ("Virtuous Vodka", "Sweden", null, SpiritCategory.Vodka),
        ("Spirit of Hven", "Sweden", null, SpiritCategory.Vodka),
        ("Purist Vodka", "Sweden", null, SpiritCategory.Vodka),
        ("Vusa Vodka", "South Africa", null, SpiritCategory.Vodka),
        ("Bain's Vodka", "South Africa", null, SpiritCategory.Vodka),
        ("Kalak Vodka", "Ireland", null, SpiritCategory.Vodka),
        ("Boru Vodka", "Ireland", null, SpiritCategory.Vodka),
        ("Kalinska", "Lithuania", null, SpiritCategory.Vodka),
        ("Goldwasser Vodka", "Poland", null, SpiritCategory.Vodka),
        ("Belenkaya", "Russia", null, SpiritCategory.Vodka),
        ("Tsarskaya", "Russia", null, SpiritCategory.Vodka),
        ("Jewel of Russia", "Russia", null, SpiritCategory.Vodka),
        ("Kremlin Award", "Russia", null, SpiritCategory.Vodka),
        ("Rodionov & Sons", "Russia", null, SpiritCategory.Vodka),
        ("Winter Palace", "Russia", null, SpiritCategory.Vodka),
        ("Khortytsa", "Ukraine", null, SpiritCategory.Vodka),
        ("Hetman", "Ukraine", null, SpiritCategory.Vodka),
        ("Medoff", "Ukraine", null, SpiritCategory.Vodka),
        ("Prime Vodka", "Ukraine", null, SpiritCategory.Vodka),
        ("Le Philtre Vodka", "France", null, SpiritCategory.Vodka),

        ("Hennessy", "France", "Cognac", SpiritCategory.Cognac),
        ("Rémy Martin", "France", "Cognac", SpiritCategory.Cognac),
        ("Martell", "France", "Cognac", SpiritCategory.Cognac),
        ("Courvoisier", "France", "Cognac", SpiritCategory.Cognac),
        ("Camus", "France", "Cognac", SpiritCategory.Cognac),
        ("Delamain", "France", "Jarnac", SpiritCategory.Cognac),
        ("Hine", "France", "Jarnac", SpiritCategory.Cognac),
        ("Frapin", "France", "Grande Champagne", SpiritCategory.Cognac),
        ("Louis XIII", "France", "Grande Champagne", SpiritCategory.Cognac),
        ("Hardy", "France", "Cognac", SpiritCategory.Cognac),
        ("Pierre Ferrand", "France", "Cognac", SpiritCategory.Cognac),
        ("Meukow", "France", "Cognac", SpiritCategory.Cognac),
        ("Gautier", "France", "Cognac", SpiritCategory.Cognac),
        ("A.E. Dor", "France", "Jarnac", SpiritCategory.Cognac),
        ("Tesseron", "France", "Cognac", SpiritCategory.Cognac),
        ("Godet", "France", "Cognac", SpiritCategory.Cognac),
        ("Otard", "France", "Cognac", SpiritCategory.Cognac),
        ("Larsen", "France", "Cognac", SpiritCategory.Cognac),
        ("Park Cognac", "France", "Cognac", SpiritCategory.Cognac),
        ("Bache-Gabrielsen", "France", "Cognac", SpiritCategory.Cognac),
        ("ABK6", "France", "Cognac", SpiritCategory.Cognac),
        ("Monnet", "France", "Cognac", SpiritCategory.Cognac),
        ("De Luze", "France", "Cognac", SpiritCategory.Cognac),
        ("François Voyer", "France", "Grande Champagne", SpiritCategory.Cognac),
        ("Jean Fillioux", "France", "Grande Champagne", SpiritCategory.Cognac),
        ("Vallein Tercinier", "France", "Cognac", SpiritCategory.Cognac),
        ("Daniel Bouju", "France", "Grande Champagne", SpiritCategory.Cognac),
        ("Château de Montifaud", "France", "Cognac", SpiritCategory.Cognac),
        ("Michel Forgeron", "France", "Grande Champagne", SpiritCategory.Cognac),
        ("Ragnaud-Sabourin", "France", "Cognac", SpiritCategory.Cognac),
        ("Léopold Gourmel", "France", "Cognac", SpiritCategory.Cognac),
        ("Jean Grosperrin", "France", "Cognac", SpiritCategory.Cognac),
        ("Maxime Trijol", "France", "Cognac", SpiritCategory.Cognac),
        ("Lhéraud", "France", "Cognac", SpiritCategory.Cognac),
        ("Croizet", "France", "Grande Champagne", SpiritCategory.Cognac),
        ("Brillet", "France", "Cognac", SpiritCategory.Cognac),
        ("Kelt", "France", "Cognac", SpiritCategory.Cognac),
        ("Audry", "France", "Cognac", SpiritCategory.Cognac),
        ("Bourgoin Cognac", "France", "Cognac", SpiritCategory.Cognac),
        ("Jean-Luc Pasquet", "France", "Cognac", SpiritCategory.Cognac),
        ("Fanny Fougerat", "France", "Cognac", SpiritCategory.Cognac),
        ("Mauxion Selection", "France", "Cognac", SpiritCategory.Cognac),
        ("Dudognon", "France", "Cognac", SpiritCategory.Cognac),
        ("Paul Beau", "France", "Cognac", SpiritCategory.Cognac),
        ("Guillon-Painturaud", "France", "Cognac", SpiritCategory.Cognac),
        ("Navarre", "France", "Cognac", SpiritCategory.Cognac),
        ("André Petit", "France", "Cognac", SpiritCategory.Cognac),
        ("Raymond Ragnaud", "France", "Cognac", SpiritCategory.Cognac),
        ("Maison Boinaud", "France", "Cognac", SpiritCategory.Cognac),
        ("A. de Fussigny", "France", "Cognac", SpiritCategory.Cognac),

        ("Torres", "Spain", null, SpiritCategory.Brandy),
        ("Cardenal Mendoza", "Spain", "Jerez", SpiritCategory.Brandy),
        ("Carlos I", "Spain", "Jerez", SpiritCategory.Brandy),
        ("Lepanto", "Spain", "Jerez", SpiritCategory.Brandy),
        ("Osborne", "Spain", "Jerez", SpiritCategory.Brandy),
        ("Terry Centenario", "Spain", "Jerez", SpiritCategory.Brandy),
        ("Soberano", "Spain", null, SpiritCategory.Brandy),
        ("Fundador", "Spain", "Jerez", SpiritCategory.Brandy),
        ("Gran Duque de Alba", "Spain", null, SpiritCategory.Brandy),
        ("Veterano", "Spain", null, SpiritCategory.Brandy),

        ("Ararat", "Armenia", null, SpiritCategory.Brandy),
        ("Noy", "Armenia", null, SpiritCategory.Brandy),
        ("Great Valley", "Armenia", null, SpiritCategory.Brandy),
        ("Proshyan Brandy", "Armenia", null, SpiritCategory.Brandy),
        ("Artsakh Brandy Company", "Armenia", null, SpiritCategory.Brandy),
        ("Araspel", "Armenia", null, SpiritCategory.Brandy),
        ("Yerevan Brandy Factory", "Armenia", null, SpiritCategory.Brandy),
        ("Shustov", "Armenia", null, SpiritCategory.Brandy),
        ("Dvin", "Armenia", null, SpiritCategory.Brandy),
        ("Vaspurakan", "Armenia", null, SpiritCategory.Brandy),

        ("E&J Brandy", "USA", null, SpiritCategory.Brandy),
        ("Christian Brothers", "USA", null, SpiritCategory.Brandy),
        ("Korbel Brandy", "USA", "California", SpiritCategory.Brandy),
        ("Paul Masson", "USA", "California", SpiritCategory.Brandy),
        ("Germain-Robin", "USA", "California", SpiritCategory.Brandy),
        ("Copper & Kings", "USA", null, SpiritCategory.Brandy),
        ("Laird's Apple Brandy", "USA", null, SpiritCategory.Brandy),
        ("Clear Creek Distillery", "USA", null, SpiritCategory.Brandy),
        ("St. George Brandy", "USA", "California", SpiritCategory.Brandy),
        ("Keltic Brandy", "USA", null, SpiritCategory.Brandy),

        ("Vecchia Romagna", "Italy", null, SpiritCategory.Brandy),
        ("Stock 84", "Italy", null, SpiritCategory.Brandy),
        ("Buton Brandy", "Italy", null, SpiritCategory.Brandy),
        ("Antinori Brandy", "Italy", null, SpiritCategory.Brandy),
        ("Nonino", "Italy", null, SpiritCategory.Brandy),

        ("Asbach Uralt", "Germany", null, SpiritCategory.Brandy),
        ("Moritz A. Brandy", "Germany", null, SpiritCategory.Brandy),
        ("Chantré", "Germany", null, SpiritCategory.Brandy),
        ("Dujardin Imperial", "Germany", null, SpiritCategory.Brandy),
        ("Kober Brandy", "Germany", null, SpiritCategory.Brandy),

        ("Metaxa", "Greece", null, SpiritCategory.Brandy),

        ("St-Rémy", "France", null, SpiritCategory.Brandy),
        ("Sarajishvili", "Georgia", null, SpiritCategory.Brandy),
        ("Askaneli", "Georgia", null, SpiritCategory.Brandy),
        ("Kutaisi Brandy", "Georgia", null, SpiritCategory.Brandy),

        ("Patrón", "Mexico", null, SpiritCategory.Tequila),
        ("Don Julio", "Mexico", null, SpiritCategory.Tequila),
        ("Jose Cuervo", "Mexico", null, SpiritCategory.Tequila),
        ("Clase Azul", "Mexico", null, SpiritCategory.Tequila),
        ("Casamigos", "Mexico", null, SpiritCategory.Tequila),
        ("Herradura", "Mexico", null, SpiritCategory.Tequila),
        ("1800 Tequila", "Mexico", null, SpiritCategory.Tequila),
        ("Espolòn", "Mexico", null, SpiritCategory.Tequila),
        ("El Tesoro", "Mexico", null, SpiritCategory.Tequila),
        ("Tequila Ocho", "Mexico", null, SpiritCategory.Tequila),
        ("Fortaleza", "Mexico", null, SpiritCategory.Tequila),
        ("Cazadores", "Mexico", null, SpiritCategory.Tequila),
        ("Código 1530", "Mexico", null, SpiritCategory.Tequila),
        ("Volcan de Mi Tierra", "Mexico", null, SpiritCategory.Tequila),
        ("Casa Dragones", "Mexico", null, SpiritCategory.Tequila),
        ("Gran Centenario", "Mexico", null, SpiritCategory.Tequila),
        ("Arette", "Mexico", null, SpiritCategory.Tequila),
        ("Siete Leguas", "Mexico", null, SpiritCategory.Tequila),
        ("Tapatio", "Mexico", null, SpiritCategory.Tequila),
        ("Cascahuín", "Mexico", null, SpiritCategory.Tequila),
        ("Don Fulano", "Mexico", null, SpiritCategory.Tequila),
        ("ArteNOM", "Mexico", null, SpiritCategory.Tequila),
        ("G4", "Mexico", null, SpiritCategory.Tequila),
        ("LALO", "Mexico", null, SpiritCategory.Tequila),
        ("El Tequileño", "Mexico", null, SpiritCategory.Tequila),
        ("Tres Agaves", "Mexico", null, SpiritCategory.Tequila),
        ("Cierto", "Mexico", null, SpiritCategory.Tequila),
        ("Fuenteseca", "Mexico", null, SpiritCategory.Tequila),
        ("Don Nacho", "Mexico", null, SpiritCategory.Tequila),
        ("Corralejo", "Mexico", null, SpiritCategory.Tequila),
        ("Teremana", "Mexico", null, SpiritCategory.Tequila),
        ("818 Tequila", "Mexico", null, SpiritCategory.Tequila),
        ("Avión", "Mexico", null, SpiritCategory.Tequila),
        ("Sauza", "Mexico", null, SpiritCategory.Tequila),
        ("Tres Generaciones", "Mexico", null, SpiritCategory.Tequila),
        ("Milagro", "Mexico", null, SpiritCategory.Tequila),
        ("Olmeca Altos", "Mexico", null, SpiritCategory.Tequila),
        ("Olmeca", "Mexico", null, SpiritCategory.Tequila),
        ("Gran Orendain", "Mexico", null, SpiritCategory.Tequila),
        ("Orendain", "Mexico", null, SpiritCategory.Tequila),
        ("Chamucos", "Mexico", null, SpiritCategory.Tequila),
        ("Siempre", "Mexico", null, SpiritCategory.Tequila),
        ("Partida", "Mexico", null, SpiritCategory.Tequila),
        ("Pasote", "Mexico", null, SpiritCategory.Tequila),
        ("Purasangre", "Mexico", null, SpiritCategory.Tequila),
        ("El Mayor", "Mexico", null, SpiritCategory.Tequila),
        ("Cimarrón", "Mexico", null, SpiritCategory.Tequila),
        ("Gran Dovejo", "Mexico", null, SpiritCategory.Tequila),
        ("Aha Yeto", "Mexico", null, SpiritCategory.Tequila),
        ("Azunia", "Mexico", null, SpiritCategory.Tequila),
        ("Roca Patrón", "Mexico", null, SpiritCategory.Tequila),
        ("Maestro Dobel", "Mexico", null, SpiritCategory.Tequila),
        ("Reserva de la Familia", "Mexico", null, SpiritCategory.Tequila),
        ("Cenote", "Mexico", null, SpiritCategory.Tequila),
        ("Mijenta", "Mexico", null, SpiritCategory.Tequila),
        ("Yéyo", "Mexico", null, SpiritCategory.Tequila),
        ("Alquimia", "Mexico", null, SpiritCategory.Tequila),
        ("Aldez", "Mexico", null, SpiritCategory.Tequila),
        ("Casa Noble", "Mexico", null, SpiritCategory.Tequila),
        ("Hussong's", "Mexico", null, SpiritCategory.Tequila),
        ("Hiatus", "Mexico", null, SpiritCategory.Tequila),
        ("Suerte", "Mexico", null, SpiritCategory.Tequila),
        ("Insolito", "Mexico", null, SpiritCategory.Tequila),
        ("Mijares", "Mexico", null, SpiritCategory.Tequila),
        ("Dos Primos", "Mexico", null, SpiritCategory.Tequila),
        ("El Bandido Yankee", "Mexico", null, SpiritCategory.Tequila),
        ("Cantera Negra", "Mexico", null, SpiritCategory.Tequila),
        ("Siempre Vivo", "Mexico", null, SpiritCategory.Tequila),
        ("Tromba", "Mexico", null, SpiritCategory.Tequila),
        ("Adictivo", "Mexico", null, SpiritCategory.Tequila),
        ("Don Ramon", "Mexico", null, SpiritCategory.Tequila),
        ("Casa Maestri", "Mexico", null, SpiritCategory.Tequila),
        ("Tequila Trujillo", "Mexico", null, SpiritCategory.Tequila),
        ("Gran Patron", "Mexico", null, SpiritCategory.Tequila),
        ("Cava de Oro", "Mexico", null, SpiritCategory.Tequila),
        ("Don Cayo", "Mexico", null, SpiritCategory.Tequila),
        ("Don Modesto", "Mexico", null, SpiritCategory.Tequila),
        ("El Jimador", "Mexico", null, SpiritCategory.Tequila),
        ("Pueblo Viejo", "Mexico", null, SpiritCategory.Tequila),
        ("Campo Azul", "Mexico", null, SpiritCategory.Tequila),
        ("Los Arango", "Mexico", null, SpiritCategory.Tequila),
        ("Los Azulejos", "Mexico", null, SpiritCategory.Tequila),
        ("Casino Azul", "Mexico", null, SpiritCategory.Tequila),
        ("Don Eduardo", "Mexico", null, SpiritCategory.Tequila),
        ("Agavales", "Mexico", null, SpiritCategory.Tequila),
        ("Tonala", "Mexico", null, SpiritCategory.Tequila),
        ("Kah", "Mexico", null, SpiritCategory.Tequila),
        ("Exotico", "Mexico", null, SpiritCategory.Tequila),
        ("Mi Campo", "Mexico", null, SpiritCategory.Tequila),
        ("Cabo Wabo", "Mexico", null, SpiritCategory.Tequila),
        ("Don Abraham", "Mexico", null, SpiritCategory.Tequila),
        ("Lunazul", "Mexico", null, SpiritCategory.Tequila),
        ("Rooster Rojo", "Mexico", null, SpiritCategory.Tequila),
        ("Aguasol", "Mexico", null, SpiritCategory.Tequila),
        ("Amatitena", "Mexico", null, SpiritCategory.Tequila),
        ("La Gritona", "Mexico", null, SpiritCategory.Tequila),
        ("CaliFino", "Mexico", null, SpiritCategory.Tequila),
        ("Tears of Llorona", "Mexico", null, SpiritCategory.Tequila),
        ("123 Organic Tequila", "Mexico", null, SpiritCategory.Tequila),
        ("Tierra Noble", "Mexico", null, SpiritCategory.Tequila),

        ("Gordon's", "United Kingdom", null, SpiritCategory.Gin),
        ("Tanqueray", "United Kingdom", null, SpiritCategory.Gin),
        ("Bombay Sapphire", "United Kingdom", null, SpiritCategory.Gin),
        ("Beefeater", "United Kingdom", null, SpiritCategory.Gin),
        ("Plymouth Gin", "United Kingdom", null, SpiritCategory.Gin),
        ("Hendrick's", "United Kingdom", "Scotland", SpiritCategory.Gin),
        ("The Botanist", "United Kingdom", "Scotland", SpiritCategory.Gin),
        ("Martin Miller's", "United Kingdom", null, SpiritCategory.Gin),
        ("Sipsmith", "United Kingdom", null, SpiritCategory.Gin),
        ("Whitley Neill", "United Kingdom", null, SpiritCategory.Gin),
        ("Bloom", "United Kingdom", null, SpiritCategory.Gin),
        ("Broker's", "United Kingdom", null, SpiritCategory.Gin),
        ("Bulldog", "United Kingdom", null, SpiritCategory.Gin),
        ("Silent Pool", "United Kingdom", null, SpiritCategory.Gin),
        ("Portobello Road", "United Kingdom", null, SpiritCategory.Gin),
        ("Bathtub Gin", "United Kingdom", null, SpiritCategory.Gin),
        ("No.3 London Dry Gin", "United Kingdom", null, SpiritCategory.Gin),
        ("Warner's", "United Kingdom", null, SpiritCategory.Gin),
        ("Opihr", "United Kingdom", null, SpiritCategory.Gin),
        ("Cotswolds Gin", "United Kingdom", null, SpiritCategory.Gin),

        ("Gin Mare", "Spain", null, SpiritCategory.Gin),
        ("Larios", "Spain", null, SpiritCategory.Gin),
        ("Nordés", "Spain", null, SpiritCategory.Gin),
        ("MG Gin", "Spain", null, SpiritCategory.Gin),
        ("Master's Gin", "Spain", null, SpiritCategory.Gin),
        ("Le Tribute Gin", "Spain", null, SpiritCategory.Gin),
        ("Puerto de Indias", "Spain", null, SpiritCategory.Gin),
        ("Mombasa Club", "Spain", null, SpiritCategory.Gin),
        ("Level Gin", "Spain", null, SpiritCategory.Gin),
        ("GinRaw", "Spain", null, SpiritCategory.Gin),

        ("Monkey 47", "Germany", null, SpiritCategory.Gin),
        ("Siegfried Rheinland Dry Gin", "Germany", null, SpiritCategory.Gin),
        ("Elephant Gin", "Germany", null, SpiritCategory.Gin),
        ("Windspiel Gin", "Germany", null, SpiritCategory.Gin),
        ("Ferdinand's Saar Dry Gin", "Germany", null, SpiritCategory.Gin),
        ("The Duke Gin", "Germany", null, SpiritCategory.Gin),
        ("Adler Berlin Dry Gin", "Germany", null, SpiritCategory.Gin),
        ("Skin Gin", "Germany", null, SpiritCategory.Gin),
        ("BIRDS Gin", "Germany", null, SpiritCategory.Gin),
        ("Bavarka Gin", "Germany", null, SpiritCategory.Gin),

        ("Bols Genever", "Netherlands", null, SpiritCategory.Gin),
        ("Bobby's Gin", "Netherlands", null, SpiritCategory.Gin),
        ("Zuidam Dutch Courage", "Netherlands", null, SpiritCategory.Gin),
        ("Rutte Dry Gin", "Netherlands", null, SpiritCategory.Gin),
        ("VL92 Gin", "Netherlands", null, SpiritCategory.Gin),

        ("Citadelle Gin", "France", null, SpiritCategory.Gin),
        ("G'Vine", "France", null, SpiritCategory.Gin),
        ("Christian Drouin Le Gin", "France", null, SpiritCategory.Gin),
        ("Generous Gin", "France", null, SpiritCategory.Gin),
        ("June Gin", "France", null, SpiritCategory.Gin),

        ("Aviation Gin", "USA", null, SpiritCategory.Gin),
        ("Junipero Gin", "USA", null, SpiritCategory.Gin),
        ("St. George Gin", "USA", null, SpiritCategory.Gin),
        ("Bluecoat Gin", "USA", null, SpiritCategory.Gin),
        ("Death's Door Gin", "USA", null, SpiritCategory.Gin),
        ("Barr Hill Gin", "USA", null, SpiritCategory.Gin),
        ("Gray Whale Gin", "USA", null, SpiritCategory.Gin),
        ("Uncle Val's", "USA", null, SpiritCategory.Gin),
        ("New Amsterdam Gin", "USA", null, SpiritCategory.Gin),
        ("FEW Gin", "USA", null, SpiritCategory.Gin),

        ("Malfy Gin", "Italy", null, SpiritCategory.Gin),
        ("Engine Gin", "Italy", null, SpiritCategory.Gin),
        ("Malfy Rosa", "Italy", null, SpiritCategory.Gin),
        ("VII Hills Gin", "Italy", null, SpiritCategory.Gin),
        ("Portofino Gin", "Italy", null, SpiritCategory.Gin),

        ("Roku Gin", "Japan", null, SpiritCategory.Gin),
        ("Ki No Bi", "Japan", null, SpiritCategory.Gin),
        ("Etsu Gin", "Japan", null, SpiritCategory.Gin),
        ("Nikka Coffey Gin", "Japan", null, SpiritCategory.Gin),
        ("Sakurao Gin", "Japan", null, SpiritCategory.Gin),

        ("Four Pillars", "Australia", null, SpiritCategory.Gin),
        ("Never Never", "Australia", null, SpiritCategory.Gin),
        ("Archie Rose Gin", "Australia", null, SpiritCategory.Gin),
        ("West Winds Gin", "Australia", null, SpiritCategory.Gin),
        ("Ink Gin", "Australia", null, SpiritCategory.Gin),

        ("Drumshanbo Gunpowder Gin", "Ireland", null, SpiritCategory.Gin),
        ("Minke Gin", "Ireland", null, SpiritCategory.Gin),
        ("Bertha's Revenge", "Ireland", null, SpiritCategory.Gin),
        ("Dingle Gin", "Ireland", null, SpiritCategory.Gin),
        ("Shortcross Gin", "Ireland", null, SpiritCategory.Gin),

        ("Scapegrace", "New Zealand", null, SpiritCategory.Gin),
        ("Broken Heart Gin", "New Zealand", null, SpiritCategory.Gin),
        ("Cape Fynbos Gin", "South Africa", null, SpiritCategory.Gin),
        ("Inverroche Gin", "South Africa", null, SpiritCategory.Gin),
        ("Musgrave Gin", "South Africa", null, SpiritCategory.Gin),
        ("Kyrö Gin", "Finland", null, SpiritCategory.Gin),
        ("Mikkeller Botanical Gin", "Denmark", null, SpiritCategory.Gin),
        ("Harahorn Gin", "Norway", null, SpiritCategory.Gin),
        ("Bareksten Gin", "Norway", null, SpiritCategory.Gin),
        ("Hernö Gin", "Sweden", null, SpiritCategory.Gin),
        ("Malfy Originale", "Italy", null, SpiritCategory.Gin),
        ("Jodhpur Gin", "Spain", null, SpiritCategory.Gin),
        ("Sharish Gin", "Portugal", null, SpiritCategory.Gin),
        ("Adamus Gin", "Portugal", null, SpiritCategory.Gin),
        ("Black Pig Gin", "Portugal", null, SpiritCategory.Gin),
        ("Gin Sul", "Germany", null, SpiritCategory.Gin),
        ("Akori Gin", "Spain", null, SpiritCategory.Gin),
        ("Marylebone Gin", "United Kingdom", null, SpiritCategory.Gin),
        ("Liverpool Gin", "United Kingdom", null, SpiritCategory.Gin),
        ("Edinburgh Gin", "United Kingdom", "Scotland", SpiritCategory.Gin),
    };
}
